services:
  status-app:
    build: .
    container_name: status-app
    ports:
      - "8080:8080"
    environment:
      DD_API_KEY: ${DD_API_KEY}
      DD_SITE: us5.datadoghq.com
      DD_SERVICE: status-app
      DD_ENV: local
      DD_LOGS_ENABLED: "true"
