#this is context properties
#Sat May 23 14:59:58 IST 2026
mySQL_Database=aiops_rc
mySQL_Password=enc\:routine.encryption.key.v1\:p63Igcb0RGr3h+WgFj1FXZRLvrfzuyzeS9WuOMPgpKmwD0hWtHg\=
mySQL_Port=3306
mySQL_AdditionalParams=noDatetimeStringSync\=true
mySQL_Server=127.0.0.1
mySQL_Login=root
postqreSQL_Port=5432
postqreSQL_Schema=public
postqreSQL_Server=127.0.0.1
postqreSQL_Login=postgres
postqreSQL_Database=aiops_rc
postqreSQL_Password=enc\:routine.encryption.key.v1\:v/9WmuxxscAJPPU0LDTtz1mRRsNmfAqCFXd7D3hbd9YxW8LeQ/k\=
postqreSQL_AdditionalParams=
