apiVersion: v1
kind: Secret
metadata:
  name: agent-manager-secrets
type: Opaque
stringData:
  # The postgres service will be running on port 5432, named 'postgres-service'
  MAIN_SERVER_DATABASE_URL: "postgresql://postgres:admin@host.docker.internal:5432/agent_management"
  AGENT_SERVER_DATABASE_URL: "postgresql+asyncpg://postgres:admin@host.docker.internal:5432/agent_server"

  ENCRYPTION_KEY: ""
  
  # MAIN_SERVER_DATABASE_URL=postgresql://postgres:admin@localhost:5432/agent_management
  # AGENT_SERVER_DATABASE_URL=postgresql+asyncpg://postgres:admin@localhost:5432/agent_server
  
  # Add other API keys here
  # OPENAI_API_KEY: "your_api_key_here"
  # SERVICENOW_INSTANCE_URL: "https://your_instance.service-now.com"
  # SERVICENOW_USERNAME: "admin"
  # SERVICENOW_PASSWORD: "password"
  # SERVICENOW_AUTH_TYPE: "basic"
