## MySQL Database Connection
#spring.datasource.url=jdbc:mysql://localhost:3306/mcp_tools?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=Cyber@1234
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## JPA / Hibernate Settings
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.mvc.dispatch-options-request=true



#PostgreSQL Database Connection
#spring.datasource.url=jdbc:postgresql://localhost:5432/rc_aiops
#spring.datasource.username=postgres
#spring.datasource.password=Admin@1234
#spring.datasource.driver-class-name=org.postgresql.Driver


spring.datasource.url=jdbc:postgresql://146.148.94.213:5432/agent_management
spring.datasource.username=postgres
spring.datasource.password=Admin_123
spring.datasource.driver-class-name=org.postgresql.Driver
#
## JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}


spring.mvc.async.request-timeout=0
server.tomcat.max-threads=200
