server:
  port: 8080

status-app:
  build: .
  container_name: status-app
  ports:
    - "8080:8080"
  environment:
    SPRING_PROFILES_ACTIVE: docker
    DD_SERVICE: status-app
    DD_ENV: local
    DD_VERSION: 1.0.0
  labels:
    com.datadoghq.ad.logs: >-
      [{
        "source": "java",
        "service": "status-app",
        "tags": ["env:local"]
      }]

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  datadog:
    metrics:
      export:
        enabled: false
        api-key: ${DD_API_KEY}
        uri: https://api.us5.datadoghq.com
        step: 30s

logging:
  level:
    root: INFO
    com.rc.customerapp: INFO