// ============================================================
// DocFlow AI — Mock data store (POC)
// Users, roles, and seeded EPC/Construction documents for the
// demo project SPCL (Shapoorji Pallonji-type usage, spec §8).
// ============================================================

const ROLES = {
  VIEWER: "Viewer",
  ENGINEER: "Contributor/Engineer",
  REVIEWER: "Reviewer/Approver",
  DOC_CONTROLLER: "Document Controller",
  CONTRACTOR: "Contractor/Subcontractor",
  PM: "Project Manager",
  ADMIN: "Admin/Auditor",
};

// All demo passwords are "demo123" (POC only — never do this in production).
const USERS = [
  {
    user_id: "u-priya",
    username: "maha",
    display_name: "Maha Al-Ghamdi",
    role: ROLES.DOC_CONTROLLER,
    org: "SP Engineering (Main Contractor)",
    projects: ["SPCL"],
    disciplines: ["ALL"],
    password: "demo123",
  },
  {
    user_id: "u-rajesh",
    username: "khalid",
    display_name: "Khalid Al-Mutairi",
    role: ROLES.REVIEWER,
    org: "SP Engineering (Main Contractor)",
    projects: ["SPCL"],
    disciplines: ["MEP", "ELE"],
    password: "demo123",
  },
  {
    user_id: "u-anil",
    username: "omar",
    display_name: "Omar Al-Harbi",
    role: ROLES.ENGINEER,
    org: "SP Engineering (Main Contractor)",
    projects: ["SPCL"],
    disciplines: ["CIV", "STR"],
    password: "demo123",
  },
  {
    user_id: "u-meena",
    username: "noura",
    display_name: "Noura Al-Qahtani",
    role: ROLES.PM,
    org: "SP Engineering (Main Contractor)",
    projects: ["SPCL"],
    disciplines: ["ALL"],
    password: "demo123",
  },
  {
    user_id: "u-vendor",
    username: "yousef",
    display_name: "Yousef Al-Sabah",
    role: ROLES.CONTRACTOR,
    org: "CoolAir HVAC Systems (Subcontractor)",
    projects: ["SPCL"],
    disciplines: ["MEP"],
    password: "demo123",
  },
  {
    user_id: "u-admin",
    username: "layla",
    display_name: "Layla Al-Rashidi",
    role: ROLES.ADMIN,
    org: "SP Engineering (Main Contractor)",
    projects: ["SPCL", "LTRM"],
    disciplines: ["ALL"],
    password: "demo123",
  },
];

// today is treated as 2026-07-19 for due-date / overdue logic
const TODAY = "2026-07-19";

// Document types & disciplines offered when creating a new document,
// plus the numbering convention (§8): [Project]-[Discipline]-[DocType]-[Sequence]-[Rev]
const DOC_TYPES = [
  "Drawing",
  "RFI",
  "Submittal/MAR",
  "NCR",
  "Method Statement",
  "BOQ/Contract",
  "MOM",
  "Transmittal",
  "Inspection Request",
  "Test Certificate",
];
const DISCIPLINES = ["MEP", "CIV", "STR", "ARC", "ELE", "COM", "QAQ", "HSE"];
const TYPE_CODES = {
  "Drawing": "DWG",
  "RFI": "RFI",
  "Submittal/MAR": "MAR",
  "NCR": "NCR",
  "Method Statement": "MS",
  "BOQ/Contract": "BOQ",
  "MOM": "MOM",
  "Transmittal": "TRN",
  "Inspection Request": "IR",
  "Test Certificate": "TC",
};
// Drawings/MARs/Method Statements revise A, B, C…; transactional doc types revise 0, 1, 2…
const LETTERED_REVISION_TYPES = ["Drawing", "Submittal/MAR", "Method Statement"];

const DOCUMENTS = [
  {
    doc_id: "d-0452",
    doc_number: "SPCL-MEP-DWG-0452-C",
    title: "Chilled Water Piping Layout — Tower B, Levels 12–18",
    type: "Drawing",
    discipline: "MEP",
    revision: "C",
    status: "PENDING REVIEW",
    project_id: "SPCL",
    originator: "u-vendor",
    originator_org: "CoolAir HVAC Systems (Subcontractor)",
    current_assignee: "u-rajesh",
    distribution_list: ["u-rajesh", "u-priya", "u-meena", "u-vendor", "u-admin"],
    submitted_date: "2026-07-06",
    due_date: "2026-07-20",
    closed_date: null,
    confidentiality: "Internal",
    comments: [
      { author: "u-priya", role: ROLES.DOC_CONTROLLER, timestamp: "2026-07-06 10:14", text: "Rev C received via transmittal TRN-2026-0198. Routed to MEP review. Supersedes Rev B." },
      { author: "u-rajesh", role: ROLES.REVIEWER, timestamp: "2026-07-09 16:40", text: "Riser shaft clash at L14 flagged in Rev B appears resolved. Verifying insulation spec against MEP-SPC-0031 before sign-off." },
      { author: "u-vendor", role: ROLES.CONTRACTOR, timestamp: "2026-07-10 09:05", text: "Insulation updated to 32mm nitrile as per Code 2 comment on Rev B. See sheet 7 note 4." },
    ],
    revision_history: [
      { revision: "A", date: "2026-05-11", change_summary: "Initial issue for review.", uploaded_by: "u-vendor" },
      { revision: "B", date: "2026-06-02", change_summary: "Rerouted CHW supply at L14 to clear cable tray; Code 3 comments incorporated.", uploaded_by: "u-vendor" },
      { revision: "C", date: "2026-07-06", change_summary: "Insulation spec updated to 32mm nitrile; valve tags added L12–L18.", uploaded_by: "u-vendor" },
    ],
    workflow_trail: [
      { step: "Rev A Review", actor: "u-rajesh", decision: "Code 3 — Revise & Resubmit", date: "2026-05-25" },
      { step: "Rev B Review", actor: "u-rajesh", decision: "Code 2 — Approved with Comments", date: "2026-06-18" },
      { step: "Rev C Review", actor: "u-rajesh", decision: "Pending", date: null },
    ],
    attachments: [
      { file_name: "SPCL-MEP-DWG-0452-C.pdf", type: "PDF", size: "8.4 MB", uploaded_by: "u-vendor", date: "2026-07-06" },
      { file_name: "valve-schedule-L12-18.xlsx", type: "XLSX", size: "212 KB", uploaded_by: "u-vendor", date: "2026-07-06" },
    ],
  },
  {
    doc_id: "d-0117",
    doc_number: "SPCL-MEP-RFI-0117-0",
    title: "RFI: Ceiling void clearance for FCU-14 series, Tower B L15",
    type: "RFI",
    discipline: "MEP",
    revision: "0",
    status: "PENDING REVIEW",
    project_id: "SPCL",
    originator: "u-vendor",
    originator_org: "CoolAir HVAC Systems (Subcontractor)",
    current_assignee: "u-rajesh",
    distribution_list: ["u-rajesh", "u-priya", "u-vendor", "u-admin"],
    submitted_date: "2026-07-11",
    due_date: "2026-07-18",
    closed_date: null,
    confidentiality: "Internal",
    comments: [
      { author: "u-vendor", role: ROLES.CONTRACTOR, timestamp: "2026-07-11 11:22", text: "Ceiling void at L15 grid C4–C7 measures 380mm vs 450mm assumed in design. Please confirm if FCU-14 can be substituted with slim-line unit or void increased." },
      { author: "u-priya", role: ROLES.DOC_CONTROLLER, timestamp: "2026-07-11 14:02", text: "Logged and routed to MEP lead. Contractual response due 7 days: 18-Jul." },
    ],
    revision_history: [
      { revision: "0", date: "2026-07-11", change_summary: "RFI raised.", uploaded_by: "u-vendor" },
    ],
    workflow_trail: [
      { step: "Response", actor: "u-rajesh", decision: "Pending", date: null },
    ],
    attachments: [
      { file_name: "site-photo-L15-void.jpg", type: "JPG", size: "3.1 MB", uploaded_by: "u-vendor", date: "2026-07-11" },
    ],
  },
  {
    doc_id: "d-0089",
    doc_number: "SPCL-CIV-DWG-0089-B",
    title: "Podium Slab Reinforcement Details — Zone 3",
    type: "Drawing",
    discipline: "CIV",
    revision: "B",
    status: "REVISE & RESUBMIT",
    project_id: "SPCL",
    originator: "u-anil",
    originator_org: "SP Engineering (Main Contractor)",
    current_assignee: "u-anil",
    distribution_list: ["u-anil", "u-priya", "u-meena", "u-admin"],
    submitted_date: "2026-06-20",
    due_date: "2026-07-15",
    closed_date: null,
    confidentiality: "Internal",
    comments: [
      { author: "u-meena", role: ROLES.PM, timestamp: "2026-07-02 15:30", text: "Code 3. Bar bending schedule inconsistent with drawing at grid E5 — BBS shows T20@150, drawing notes T16@150. Reconcile and resubmit." },
      { author: "u-anil", role: ROLES.ENGINEER, timestamp: "2026-07-03 09:12", text: "Acknowledged. Structural consultant confirmed T20@150 governs; correcting drawing note. Target resubmission 16-Jul." },
    ],
    revision_history: [
      { revision: "A", date: "2026-05-28", change_summary: "Initial issue.", uploaded_by: "u-anil" },
      { revision: "B", date: "2026-06-20", change_summary: "Zone 3 openings added per architectural rev; BBS updated.", uploaded_by: "u-anil" },
    ],
    workflow_trail: [
      { step: "Rev A Review", actor: "u-meena", decision: "Code 2 — Approved with Comments", date: "2026-06-10" },
      { step: "Rev B Review", actor: "u-meena", decision: "Code 3 — Revise & Resubmit", date: "2026-07-02" },
    ],
    attachments: [
      { file_name: "SPCL-CIV-DWG-0089-B.pdf", type: "PDF", size: "12.7 MB", uploaded_by: "u-anil", date: "2026-06-20" },
    ],
  },
  {
    doc_id: "d-0203",
    doc_number: "SPCL-MEP-MAR-0203-A",
    title: "Material Approval Request — VRF Outdoor Units (Daikin VRV-X)",
    type: "Submittal/MAR",
    discipline: "MEP",
    revision: "A",
    status: "APPROVED W/ COMMENTS",
    project_id: "SPCL",
    originator: "u-vendor",
    originator_org: "CoolAir HVAC Systems (Subcontractor)",
    current_assignee: null,
    distribution_list: ["u-rajesh", "u-priya", "u-vendor", "u-meena", "u-admin"],
    submitted_date: "2026-06-08",
    due_date: "2026-06-22",
    closed_date: "2026-06-19",
    confidentiality: "Internal",
    comments: [
      { author: "u-rajesh", role: ROLES.REVIEWER, timestamp: "2026-06-19 13:45", text: "Code 2. Approved with comments: submit type test certificates for L14+ units before delivery; confirm refrigerant pipe lengths within manufacturer limits for roof-mounted condensers." },
      { author: "u-vendor", role: ROLES.CONTRACTOR, timestamp: "2026-06-20 10:30", text: "Noted. Test certificates to follow under separate submittal by 30-Jul." },
    ],
    revision_history: [
      { revision: "A", date: "2026-06-08", change_summary: "Initial MAR submission with datasheets and compliance statement.", uploaded_by: "u-vendor" },
    ],
    workflow_trail: [
      { step: "Rev A Review", actor: "u-rajesh", decision: "Code 2 — Approved with Comments", date: "2026-06-19" },
    ],
    attachments: [
      { file_name: "VRV-X-datasheets.pdf", type: "PDF", size: "5.6 MB", uploaded_by: "u-vendor", date: "2026-06-08" },
      { file_name: "compliance-statement.docx", type: "DOCX", size: "84 KB", uploaded_by: "u-vendor", date: "2026-06-08" },
    ],
  },
  {
    doc_id: "d-0031",
    doc_number: "SPCL-QAQ-NCR-0031-0",
    title: "NCR: Honeycombing in core wall pour, Tower A L22",
    type: "NCR",
    discipline: "CIV",
    revision: "0",
    status: "PENDING REVIEW",
    project_id: "SPCL",
    originator: "u-priya",
    originator_org: "SP Engineering (Main Contractor)",
    current_assignee: "u-anil",
    distribution_list: ["u-anil", "u-priya", "u-meena", "u-admin"],
    submitted_date: "2026-07-14",
    due_date: "2026-07-21",
    closed_date: null,
    confidentiality: "Restricted",
    comments: [
      { author: "u-priya", role: ROLES.DOC_CONTROLLER, timestamp: "2026-07-14 08:50", text: "NCR raised by QA/QC after formwork strike. Honeycombing observed grid B2, approx 0.6m x 0.3m. Disposition proposal required from Civil within 7 days." },
    ],
    revision_history: [
      { revision: "0", date: "2026-07-14", change_summary: "NCR raised.", uploaded_by: "u-priya" },
    ],
    workflow_trail: [
      { step: "Disposition Proposal", actor: "u-anil", decision: "Pending", date: null },
      { step: "PM Approval", actor: "u-meena", decision: "Not started", date: null },
    ],
    attachments: [
      { file_name: "ncr-0031-photos.pdf", type: "PDF", size: "6.9 MB", uploaded_by: "u-priya", date: "2026-07-14" },
    ],
  },
  {
    doc_id: "d-0555",
    doc_number: "SPCL-STR-DWG-0555-A",
    title: "Steel Connection Details — Podium Transfer Truss PT-2",
    type: "Drawing",
    discipline: "STR",
    revision: "A",
    status: "UNDER REVIEW",
    project_id: "SPCL",
    originator: "u-anil",
    originator_org: "SP Engineering (Main Contractor)",
    current_assignee: "u-meena",
    distribution_list: ["u-anil", "u-priya", "u-meena", "u-admin"],
    submitted_date: "2026-07-10",
    due_date: "2026-07-24",
    closed_date: null,
    confidentiality: "Internal",
    comments: [],
    revision_history: [
      { revision: "A", date: "2026-07-10", change_summary: "Initial issue for review.", uploaded_by: "u-anil" },
    ],
    workflow_trail: [
      { step: "Rev A Review", actor: "u-meena", decision: "Pending", date: null },
    ],
    attachments: [
      { file_name: "SPCL-STR-DWG-0555-A.pdf", type: "PDF", size: "9.2 MB", uploaded_by: "u-anil", date: "2026-07-10" },
    ],
  },
  {
    doc_id: "d-076",
    doc_number: "SPCL-MEP-MS-0076-B",
    title: "Method Statement — Chiller Plant Room Installation & Rigging",
    type: "Method Statement",
    discipline: "MEP",
    revision: "B",
    status: "APPROVED",
    project_id: "SPCL",
    originator: "u-vendor",
    originator_org: "CoolAir HVAC Systems (Subcontractor)",
    current_assignee: null,
    distribution_list: ["u-rajesh", "u-priya", "u-vendor", "u-meena", "u-admin"],
    submitted_date: "2026-05-30",
    due_date: "2026-06-13",
    closed_date: "2026-06-11",
    confidentiality: "Internal",
    comments: [
      { author: "u-rajesh", role: ROLES.REVIEWER, timestamp: "2026-06-11 12:00", text: "Code 1. Approved. Rigging plan and lift permits verified against site logistics plan rev 4." },
    ],
    revision_history: [
      { revision: "A", date: "2026-05-12", change_summary: "Initial issue.", uploaded_by: "u-vendor" },
      { revision: "B", date: "2026-05-30", change_summary: "Crane position revised; hot-works permit section added per Code 3 comments.", uploaded_by: "u-vendor" },
    ],
    workflow_trail: [
      { step: "Rev A Review", actor: "u-rajesh", decision: "Code 3 — Revise & Resubmit", date: "2026-05-22" },
      { step: "Rev B Review", actor: "u-rajesh", decision: "Code 1 — Approved", date: "2026-06-11" },
    ],
    attachments: [
      { file_name: "MS-chiller-install-revB.pdf", type: "PDF", size: "2.3 MB", uploaded_by: "u-vendor", date: "2026-05-30" },
    ],
  },
  {
    doc_id: "d-0012",
    doc_number: "SPCL-COM-BOQ-0012-1",
    title: "BOQ Variation 12 — Facade Package Rate Revision",
    type: "BOQ/Contract",
    discipline: "COM",
    revision: "1",
    status: "UNDER REVIEW",
    project_id: "SPCL",
    originator: "u-meena",
    originator_org: "SP Engineering (Main Contractor)",
    current_assignee: "u-meena",
    distribution_list: ["u-meena", "u-admin", "u-priya"],
    submitted_date: "2026-07-08",
    due_date: "2026-07-29",
    closed_date: null,
    confidentiality: "Commercial-in-confidence",
    commercial_value: "INR 4.82 Cr",
    comments: [
      { author: "u-meena", role: ROLES.PM, timestamp: "2026-07-08 17:20", text: "Variation covers aluminium rate escalation per contract clause 13.8. Commercial review with client QS scheduled 22-Jul.", internal_only: true },
    ],
    revision_history: [
      { revision: "0", date: "2026-06-25", change_summary: "Initial variation draft.", uploaded_by: "u-meena" },
      { revision: "1", date: "2026-07-08", change_summary: "Rates aligned to June indices; substantiation annexure added.", uploaded_by: "u-meena" },
    ],
    workflow_trail: [
      { step: "Commercial Review", actor: "u-meena", decision: "Pending", date: null },
    ],
    attachments: [
      { file_name: "BOQ-VAR-12-rev1.xlsx", type: "XLSX", size: "540 KB", uploaded_by: "u-meena", date: "2026-07-08" },
    ],
  },
  {
    doc_id: "d-0644",
    doc_number: "SPCL-ARC-DWG-0644-D",
    title: "Lobby Finishes Plan — Tower A Ground Floor",
    type: "Drawing",
    discipline: "ARC",
    revision: "D",
    status: "SUPERSEDED",
    project_id: "SPCL",
    originator: "u-anil",
    originator_org: "SP Engineering (Main Contractor)",
    current_assignee: null,
    distribution_list: ["u-anil", "u-priya", "u-meena", "u-admin"],
    submitted_date: "2026-04-14",
    due_date: "2026-04-28",
    closed_date: "2026-06-30",
    confidentiality: "Internal",
    comments: [
      { author: "u-priya", role: ROLES.DOC_CONTROLLER, timestamp: "2026-06-30 09:00", text: "Superseded by Rev E issued under transmittal TRN-2026-0181. Retained for record." },
    ],
    revision_history: [
      { revision: "C", date: "2026-03-02", change_summary: "Stone selection updated.", uploaded_by: "u-anil" },
      { revision: "D", date: "2026-04-14", change_summary: "Reception desk relocated; floor pattern revised.", uploaded_by: "u-anil" },
    ],
    workflow_trail: [
      { step: "Rev D Review", actor: "u-meena", decision: "Code 1 — Approved", date: "2026-04-25" },
    ],
    attachments: [
      { file_name: "SPCL-ARC-DWG-0644-D.pdf", type: "PDF", size: "15.1 MB", uploaded_by: "u-anil", date: "2026-04-14" },
    ],
  },
  {
    doc_id: "d-0290",
    doc_number: "SPCL-MEP-IR-0290-0",
    title: "Inspection Request — First-fix electrical containment, Tower B L10",
    type: "Inspection Request",
    discipline: "MEP",
    revision: "0",
    status: "PENDING REVIEW",
    project_id: "SPCL",
    originator: "u-vendor",
    originator_org: "CoolAir HVAC Systems (Subcontractor)",
    current_assignee: "u-rajesh",
    distribution_list: ["u-rajesh", "u-priya", "u-vendor", "u-admin"],
    submitted_date: "2026-07-08",
    due_date: "2026-07-12",
    closed_date: null,
    confidentiality: "Internal",
    comments: [
      { author: "u-vendor", role: ROLES.CONTRACTOR, timestamp: "2026-07-08 08:15", text: "Area ready for inspection. Requesting joint inspection with consultant on containment routing and supports." },
      { author: "u-priya", role: ROLES.DOC_CONTROLLER, timestamp: "2026-07-13 10:05", text: "IR past 48h contractual response window. Escalated to MEP lead." },
    ],
    revision_history: [
      { revision: "0", date: "2026-07-08", change_summary: "IR raised.", uploaded_by: "u-vendor" },
    ],
    workflow_trail: [
      { step: "Inspection", actor: "u-rajesh", decision: "Pending", date: null },
    ],
    attachments: [],
  },
  {
    doc_id: "d-0018",
    doc_number: "SPCL-HSE-MOM-0018-0",
    title: "MOM — Weekly HSE Coordination Meeting #18",
    type: "MOM",
    discipline: "HSE",
    revision: "0",
    status: "CLOSED",
    project_id: "SPCL",
    originator: "u-priya",
    originator_org: "SP Engineering (Main Contractor)",
    current_assignee: null,
    distribution_list: ["u-priya", "u-meena", "u-anil", "u-rajesh", "u-vendor", "u-admin"],
    submitted_date: "2026-07-02",
    due_date: null,
    closed_date: "2026-07-05",
    confidentiality: "Internal",
    comments: [
      { author: "u-meena", role: ROLES.PM, timestamp: "2026-07-03 11:00", text: "Action 18.3 (edge protection L20+) owner corrected to Civil. Otherwise accurate — approved for circulation." },
    ],
    revision_history: [
      { revision: "0", date: "2026-07-02", change_summary: "Minutes issued.", uploaded_by: "u-priya" },
    ],
    workflow_trail: [
      { step: "PM Acceptance", actor: "u-meena", decision: "Accepted", date: "2026-07-03" },
    ],
    attachments: [
      { file_name: "MOM-HSE-18.pdf", type: "PDF", size: "310 KB", uploaded_by: "u-priya", date: "2026-07-02" },
    ],
  },
  {
    doc_id: "d-0301",
    doc_number: "SPCL-MEP-TRN-0198-0",
    title: "Transmittal TRN-2026-0198 — MEP drawings batch (Rev C set, Tower B)",
    type: "Transmittal",
    discipline: "MEP",
    revision: "0",
    status: "CLOSED",
    project_id: "SPCL",
    originator: "u-priya",
    originator_org: "SP Engineering (Main Contractor)",
    current_assignee: null,
    distribution_list: ["u-priya", "u-rajesh", "u-vendor", "u-admin"],
    submitted_date: "2026-07-06",
    due_date: null,
    closed_date: "2026-07-06",
    confidentiality: "Internal",
    comments: [],
    revision_history: [
      { revision: "0", date: "2026-07-06", change_summary: "Transmittal issued covering SPCL-MEP-DWG-0452-C and 3 associated schedules.", uploaded_by: "u-priya" },
    ],
    workflow_trail: [
      { step: "Issue", actor: "u-priya", decision: "Issued", date: "2026-07-06" },
    ],
    attachments: [],
  },
  {
    doc_id: "d-0710",
    doc_number: "SPCL-ELE-DWG-0710-B",
    title: "Single Line Diagram — Tower A Main LV Panel",
    type: "Drawing",
    discipline: "ELE",
    revision: "B",
    status: "APPROVED W/ COMMENTS",
    project_id: "SPCL",
    originator: "u-anil",
    originator_org: "SP Engineering (Main Contractor)",
    current_assignee: null,
    distribution_list: ["u-anil", "u-rajesh", "u-priya", "u-meena", "u-admin"],
    submitted_date: "2026-06-15",
    due_date: "2026-06-29",
    closed_date: "2026-06-26",
    confidentiality: "Internal",
    comments: [
      { author: "u-rajesh", role: ROLES.REVIEWER, timestamp: "2026-06-26 11:35", text: "Code 2. Approved with comments: update breaker schedule to show revised MCCB ratings for AHU feeders; coordinate spare ways count with client FM team before panel fabrication." },
      { author: "u-anil", role: ROLES.ENGINEER, timestamp: "2026-06-27 09:10", text: "Noted — breaker schedule correction will be captured in Rev C along with any FM team inputs." },
    ],
    revision_history: [
      { revision: "A", date: "2026-05-20", change_summary: "Initial issue for review.", uploaded_by: "u-anil" },
      { revision: "B", date: "2026-06-15", change_summary: "Metering section revised; earthing arrangement updated per Code 3 comments.", uploaded_by: "u-anil" },
    ],
    workflow_trail: [
      { step: "Rev A Review", actor: "u-rajesh", decision: "Code 3 — Revise & Resubmit", date: "2026-06-02" },
      { step: "Rev B Review", actor: "u-rajesh", decision: "Code 2 — Approved with Comments", date: "2026-06-26" },
    ],
    attachments: [
      { file_name: "SPCL-ELE-DWG-0710-B.pdf", type: "PDF", size: "4.8 MB", uploaded_by: "u-anil", date: "2026-06-15" },
    ],
  },
  {
    doc_id: "d-0623",
    doc_number: "SPCL-STR-DWG-0623-A",
    title: "Anchor Bolt Layout — Podium Transfer Truss Supports",
    type: "Drawing",
    discipline: "STR",
    revision: "A",
    status: "APPROVED W/ COMMENTS",
    project_id: "SPCL",
    originator: "u-anil",
    originator_org: "SP Engineering (Main Contractor)",
    current_assignee: null,
    distribution_list: ["u-anil", "u-priya", "u-meena", "u-admin"],
    submitted_date: "2026-06-28",
    due_date: "2026-07-12",
    closed_date: "2026-07-09",
    confidentiality: "Internal",
    comments: [
      { author: "u-meena", role: ROLES.PM, timestamp: "2026-07-09 14:20", text: "Code 2. Approved with comments: add setting-out tolerance note (±3mm) per structural consultant email of 05-Jul; grout spec reference to be updated to rev 2 of STR-SPC-0012." },
    ],
    revision_history: [
      { revision: "A", date: "2026-06-28", change_summary: "Initial issue for review.", uploaded_by: "u-anil" },
    ],
    workflow_trail: [
      { step: "Rev A Review", actor: "u-meena", decision: "Code 2 — Approved with Comments", date: "2026-07-09" },
    ],
    attachments: [
      { file_name: "SPCL-STR-DWG-0623-A.pdf", type: "PDF", size: "6.2 MB", uploaded_by: "u-anil", date: "2026-06-28" },
      { file_name: "anchor-bolt-schedule.xlsx", type: "XLSX", size: "96 KB", uploaded_by: "u-anil", date: "2026-06-28" },
    ],
  },
  {
    doc_id: "d-0215",
    doc_number: "SPCL-MEP-MAR-0215-A",
    title: "Material Approval Request — Fire Dampers & Actuators (Ruskin)",
    type: "Submittal/MAR",
    discipline: "MEP",
    revision: "A",
    status: "APPROVED W/ COMMENTS",
    project_id: "SPCL",
    originator: "u-vendor",
    originator_org: "CoolAir HVAC Systems (Subcontractor)",
    current_assignee: null,
    distribution_list: ["u-rajesh", "u-priya", "u-vendor", "u-admin"],
    submitted_date: "2026-06-22",
    due_date: "2026-07-06",
    closed_date: "2026-07-03",
    confidentiality: "Internal",
    comments: [
      { author: "u-rajesh", role: ROLES.REVIEWER, timestamp: "2026-07-03 10:05", text: "Code 2. Approved with comments: submit UL/FM certification for the 1.5hr rated dampers used in shaft walls; actuator voltage to be confirmed against BMS IO schedule before ordering." },
      { author: "u-vendor", role: ROLES.CONTRACTOR, timestamp: "2026-07-04 08:40", text: "UL certificates requested from manufacturer; expected within 2 weeks. Actuators confirmed 24V per BMS schedule rev 3." },
    ],
    revision_history: [
      { revision: "A", date: "2026-06-22", change_summary: "Initial MAR submission with datasheets and schedule of locations.", uploaded_by: "u-vendor" },
    ],
    workflow_trail: [
      { step: "Rev A Review", actor: "u-rajesh", decision: "Code 2 — Approved with Comments", date: "2026-07-03" },
    ],
    attachments: [
      { file_name: "fire-damper-datasheets.pdf", type: "PDF", size: "3.4 MB", uploaded_by: "u-vendor", date: "2026-06-22" },
    ],
  },
  {
    doc_id: "d-0102",
    doc_number: "SPCL-CIV-MS-0102-A",
    title: "Method Statement — Mass Concrete Pour, Podium Raft Zone 5",
    type: "Method Statement",
    discipline: "CIV",
    revision: "A",
    status: "APPROVED W/ COMMENTS",
    project_id: "SPCL",
    originator: "u-anil",
    originator_org: "SP Engineering (Main Contractor)",
    current_assignee: null,
    distribution_list: ["u-anil", "u-priya", "u-meena", "u-admin"],
    submitted_date: "2026-07-01",
    due_date: "2026-07-15",
    closed_date: "2026-07-13",
    confidentiality: "Internal",
    comments: [
      { author: "u-meena", role: ROLES.PM, timestamp: "2026-07-13 16:50", text: "Code 2. Approved with comments: include thermocouple monitoring plan for core temperature (pour depth >1.5m); night-pour lighting arrangement to be agreed with HSE before mobilisation." },
      { author: "u-anil", role: ROLES.ENGINEER, timestamp: "2026-07-14 09:25", text: "Thermocouple layout being prepared with the concrete supplier; HSE walk-through booked for 21-Jul." },
    ],
    revision_history: [
      { revision: "A", date: "2026-07-01", change_summary: "Initial issue for review.", uploaded_by: "u-anil" },
    ],
    workflow_trail: [
      { step: "Rev A Review", actor: "u-meena", decision: "Code 2 — Approved with Comments", date: "2026-07-13" },
    ],
    attachments: [
      { file_name: "MS-raft-pour-zone5.pdf", type: "PDF", size: "1.9 MB", uploaded_by: "u-anil", date: "2026-07-01" },
      { file_name: "pour-sequence-sketch.jpg", type: "JPG", size: "1.2 MB", uploaded_by: "u-anil", date: "2026-07-01" },
    ],
  },
  {
    doc_id: "d-0044",
    doc_number: "SPCL-MEP-TC-0044-0",
    title: "Test Certificate — Chilled Water Pipework Pressure Test, Tower B L12–L14",
    type: "Test Certificate",
    discipline: "MEP",
    revision: "0",
    status: "APPROVED W/ COMMENTS",
    project_id: "SPCL",
    originator: "u-vendor",
    originator_org: "CoolAir HVAC Systems (Subcontractor)",
    current_assignee: null,
    distribution_list: ["u-rajesh", "u-priya", "u-vendor", "u-admin"],
    submitted_date: "2026-07-05",
    due_date: "2026-07-19",
    closed_date: "2026-07-16",
    confidentiality: "Internal",
    comments: [
      { author: "u-rajesh", role: ROLES.REVIEWER, timestamp: "2026-07-16 13:15", text: "Code 2. Approved with comments: witness signature of consultant missing on page 2 — obtain and re-upload countersigned copy for record; retest not required as gauge calibration certificate is valid." },
      { author: "u-vendor", role: ROLES.CONTRACTOR, timestamp: "2026-07-17 10:00", text: "Consultant countersignature arranged for Monday's site visit; countersigned copy to follow." },
    ],
    revision_history: [
      { revision: "0", date: "2026-07-05", change_summary: "Test certificate submitted with gauge calibration records.", uploaded_by: "u-vendor" },
    ],
    workflow_trail: [
      { step: "Review", actor: "u-rajesh", decision: "Code 2 — Approved with Comments", date: "2026-07-16" },
    ],
    attachments: [
      { file_name: "pressure-test-cert-L12-14.pdf", type: "PDF", size: "780 KB", uploaded_by: "u-vendor", date: "2026-07-05" },
    ],
  },
  {
    doc_id: "d-0402",
    doc_number: "LTRM-CIV-DWG-0007-A",
    title: "Retaining Wall Sections — LTRM Metro Depot",
    type: "Drawing",
    discipline: "CIV",
    revision: "A",
    status: "UNDER REVIEW",
    project_id: "LTRM",
    originator: "u-admin",
    originator_org: "SP Engineering (Main Contractor)",
    current_assignee: "u-admin",
    distribution_list: ["u-admin"],
    submitted_date: "2026-07-01",
    due_date: "2026-07-22",
    closed_date: null,
    confidentiality: "Internal",
    comments: [],
    revision_history: [
      { revision: "A", date: "2026-07-01", change_summary: "Initial issue.", uploaded_by: "u-admin" },
    ],
    workflow_trail: [
      { step: "Rev A Review", actor: "u-admin", decision: "Pending", date: null },
    ],
    attachments: [],
  },
];
