#!/usr/bin/env node
require('dotenv').config();

const http = require('http');
const path = require('path');
const { randomUUID } = require('crypto');
const { createConnection } = require('./index.js');
const { StdioServerTransport } = require('@modelcontextprotocol/sdk/server/stdio.js');
const { StreamableHTTPServerTransport } = require('@modelcontextprotocol/sdk/server/streamableHttp.js');
const { ListToolsRequestSchema, CallToolRequestSchema } = require('@modelcontextprotocol/sdk/types.js');
const { sendMail } = require('./src/outlook-mail.js');

// Playwright MCP's browser_* tools (screenshots, PDFs, downloads) save relative filenames
// into the process's current working directory. We chdir into OUTPUT_DIR at startup (see
// main()) so those saves and send_email's attachmentPaths resolution agree on the same
// directory -- the agent can then attach a file it just downloaded/generated by name alone,
// with no folder mount or absolute host path required.
const OUTPUT_DIR = process.env.PLAYWRIGHT_MCP_OUTPUT_DIR || path.join(require('os').tmpdir(), 'playwright-mcp-output');

const SEND_EMAIL_TOOL = {
  name: 'send_email',
  title: 'Send Email',
  description: 'Send an email from the configured Outlook mailbox, optionally with file attachments.',
  inputSchema: {
    type: 'object',
    properties: {
      to: { type: 'string', description: 'Recipient email address, or comma-separated list of addresses' },
      subject: { type: 'string', description: 'Email subject' },
      body: { type: 'string', description: 'Email body (HTML)' },
      attachmentPaths: {
        type: 'array',
        items: { type: 'string' },
        description: 'Files to attach. A bare filename (e.g. one just saved by browser_pdf_save, browser_take_screenshot, or a download) is resolved from the shared output directory. An absolute path is used as-is.',
      },
    },
    required: ['to', 'subject', 'body'],
  },
};

function assertOutlookEnv() {
  for (const name of ['OUTLOOK_CLIENT_ID', 'OUTLOOK_CLIENT_SECRET', 'OUTLOOK_TENANT_ID', 'OUTLOOK_MAILBOX_USER']) {
    if (!process.env[name])
      throw new Error(`Missing required environment variable: ${name}`);
  }
}

function browserConfig() {
  return {
    browser: {
      browserName: 'chromium',
      // Explicit channel avoids resolving to chromium_headless_shell, which the Docker
      // image's browser stage deliberately does not install (see Dockerfile's
      // `install --no-shell chromium`).
      launchOptions: { headless: true, channel: 'chromium' },
      // Each HTTP session builds its own Server/browser context (buildServer() is called
      // per session); without isolated profiles they'd collide on the same on-disk
      // user-data-dir and fail with "Browser is already in use".
      isolated: true,
    },
    outputDir: OUTPUT_DIR,
  };
}

async function buildServer() {
  const server = await createConnection(browserConfig());

  // The underlying Server only allows one handler per request method, and playwright-core
  // already installed handlers for tools/list and tools/call. We capture those originals
  // and wrap them so send_email is added on top instead of replacing the 68 browser tools.
  const originalListTools = server._requestHandlers.get('tools/list');
  const originalCallTool = server._requestHandlers.get('tools/call');

  server.setRequestHandler(ListToolsRequestSchema, async (request, extra) => {
    const result = await originalListTools(request, extra);
    return { ...result, tools: [...result.tools, SEND_EMAIL_TOOL] };
  });

  server.setRequestHandler(CallToolRequestSchema, async (request, extra) => {
    if (request.params.name !== 'send_email')
      return originalCallTool(request, extra);

    const { to, subject, body, attachmentPaths } = request.params.arguments || {};
    // A bare filename (e.g. one just downloaded/saved by a browser_* tool) resolves
    // against OUTPUT_DIR; an absolute path is used as-is (e.g. under a mounted folder).
    const resolvedPaths = (attachmentPaths || []).map(p => path.isAbsolute(p) ? p : path.join(OUTPUT_DIR, p));
    try {
      await sendMail({ to, subject, body, attachmentPaths: resolvedPaths });
      return { content: [{ type: 'text', text: `Email sent to ${to}` }] };
    } catch (error) {
      return { content: [{ type: 'text', text: `Failed to send email: ${error.message}` }], isError: true };
    }
  });

  return server;
}

async function runStdio() {
  const server = await buildServer();
  const transport = new StdioServerTransport();
  await server.connect(transport);
}

async function runHttp(port, host) {
  // One Playwright session (and one MCP Server) per HTTP session, mirroring how
  // cli.js --port behaves: each connected client gets its own browser context.
  const sessions = new Map();

  const httpServer = http.createServer(async (req, res) => {
    if (req.method !== 'POST' || req.url !== '/mcp') {
      res.writeHead(404).end('Not found. POST MCP requests to /mcp');
      return;
    }

    const sessionId = req.headers['mcp-session-id'];
    let session = sessionId && sessions.get(sessionId);

    if (!session) {
      const server = await buildServer();
      const transport = new StreamableHTTPServerTransport({
        sessionIdGenerator: () => randomUUID(),
        onsessioninitialized: id => sessions.set(id, { server, transport }),
      });
      transport.onclose = () => {
        if (transport.sessionId)
          sessions.delete(transport.sessionId);
      };
      await server.connect(transport);
      session = { server, transport };
    }

    let body = '';
    req.on('data', chunk => { body += chunk; });
    req.on('end', async () => {
      let parsedBody;
      try {
        parsedBody = body ? JSON.parse(body) : undefined;
      } catch (error) {
        res.writeHead(400, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ error: 'Invalid JSON body' }));
        return;
      }
      await session.transport.handleRequest(req, res, parsedBody);
    });
  });

  await new Promise(resolve => httpServer.listen(port, host, resolve));
  console.error(`Playwright MCP (with send_email) listening on http://${host}:${port}/mcp`);
}

async function main() {
  assertOutlookEnv();

  require('fs').mkdirSync(OUTPUT_DIR, { recursive: true });
  process.chdir(OUTPUT_DIR);

  const port = process.env.PORT ? Number(process.env.PORT) : undefined;
  // Bind to all interfaces by default so the port is reachable when published from a
  // container (localhost inside the container is not the same as the host's localhost).
  const host = process.env.HOST || '0.0.0.0';

  if (port)
    await runHttp(port, host);
  else
    await runStdio();
}

main().catch(error => {
  console.error(error);
  process.exit(1);
});
