apiVersion: v1
kind: Service
metadata:
  name: agent-manager-service
spec:
  type: LoadBalancer # Change to ClusterIP for internal only if using an Ingress later
  selector:
    app: agent-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
