"""init

Revision ID: 5506f38fe078
Revises: 
Create Date: 2026-05-14 16:07:29.691272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5506f38fe078'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connectorconfig',
    sa.Column('connector_config_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('connector_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('connector_config_id')
    )
    op.create_table('mcpserver',
    sa.Column('mcp_server_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('server_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('auth_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auth_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('auth_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('tools_json', sa.JSON(), nullable=True),
    sa.Column('resources_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('mcp_server_id')
    )
    op.create_table('model',
    sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('isEnabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('skill',
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tools', sa.JSON(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('assets', sa.JSON(), nullable=True),
    sa.Column('scripts', sa.JSON(), nullable=True),
    sa.Column('connector_config_ids', sa.JSON(), nullable=True),
    sa.Column('mcp_server_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('skill_id')
    )
    op.create_table('agent',
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instruction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('primary_use_global', sa.Boolean(), nullable=False),
    sa.Column('primary_model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('secondary_use_global', sa.Boolean(), nullable=False),
    sa.Column('secondary_model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tertiary_use_global', sa.Boolean(), nullable=False),
    sa.Column('tertiary_model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tools', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('isEnabled', sa.Boolean(), nullable=False),
    sa.Column('connector_config_ids', sa.JSON(), nullable=True),
    sa.Column('skill_ids', sa.JSON(), nullable=True),
    sa.Column('mcp_server_ids', sa.JSON(), nullable=True),
    sa.Column('mcp_servers', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sub_agents', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['primary_model_id'], ['model.model_id'], ),
    sa.ForeignKeyConstraint(['secondary_model_id'], ['model.model_id'], ),
    sa.ForeignKeyConstraint(['tertiary_model_id'], ['model.model_id'], ),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('model_defaults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primary_model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('secondary_model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tertiary_model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['primary_model_id'], ['model.model_id'], ),
    sa.ForeignKeyConstraint(['secondary_model_id'], ['model.model_id'], ),
    sa.ForeignKeyConstraint(['tertiary_model_id'], ['model.model_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cron_expression', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.agent_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('webhook',
    sa.Column('webhook_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.agent_id'], ),
    sa.PrimaryKeyConstraint('webhook_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook')
    op.drop_table('job')
    op.drop_table('model_defaults')
    op.drop_table('agent')
    op.drop_table('skill')
    op.drop_table('model')
    op.drop_table('mcpserver')
    op.drop_table('connectorconfig')
    # ### end Alembic commands ###
